version: '3.9'
services:
  app:
    build: .
    ports:
    - "8089:8000"
    image: app:codeProject
    container_name: ContainerAPI
    command: python AuthorIdentification/manage.py runserver 0.0.0.0:8000